const mysql={
    getWXAccessToken:'SELECT * FROM wx_token WHERE openid = ? ORDER BY create_at DESC',
    addWXAccessToken:'INSERT INTO wx_token (access_token, expires_in, refresh_token, openid, scope, create_at) VALUES(?, ?, ?, ?, ?, ?)',
    getWXUserInfo:'SELECT * FROM wx_user_info WHERE unionid = ? ',
    addWXUserInfo:'INSERT INTO wx_user_info (openid, username, sex, language, city, province, country, headimgurl, privilege, unionid ) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
    getClientInfo:'SELECT * FROM oauth2_client WHERE name = ? ',
    getClients:'SELECT * FROM oauth2_client WHERE client_id = ? ',
    addClientInfo:'INSERT INTO oauth2_client (client_id, name, client_secret, redirect_uri, grant_types, scope) VALUES(?, ?, ?, ?, ?, ?)',
    getQQAccessToken:'SELECT * FROM qq_token WHERE openid = ? ORDER BY create_at DESC',
    addQQAccessToken:'INSERT INTO qq_token (access_token, expires_in, refresh_token, openid, scope, create_at) VALUES(?, ?, ?, ?, ?, ?)',
    getUserByPhone:'SELECT * FROM uc_users WHERE phone = ? ',
    getUserByEmail:'SELECT * FROM uc_users WHERE email = ? ',
    getUserByUserName:'SELECT * FROM uc_users WHERE username = ? ',
    register:'INSERT INTO uc_users(username ,password,email,salt) VALUES(?,?,?,?)',
    postEmail:'SELECT * FROM uc_post_email WHERE email_id = ? ',
    emailContent:'SELECT * FROM uc_post_email WHERE type = ? ',
    saveEmailToken:'INSERT INTO uc_active_email(email ,token,reg_date) VALUES(?,?,?) ',
    updateEmailToken:'UPDATE uc_active_email SET token = ? ,reg_date = ? where email = ?',
    getEmailToken:'SELECT * FROM uc_active_email WHERE email = ?  ',
    checkEmailToken:'SELECT * FROM uc_active_email WHERE token = ?  ',
    checkTokenByEmail:'SELECT * FROM uc_active_email WHERE email = ?  ',
    activeAccount:'UPDATE uc_active_email SET is_active = TRUE WHERE token = ? ',
    resetPassword:'UPDATE uc_users SET password = ? , salt = ? WHERE username = ? ',
}
module.exports = mysql;